Add group selectors to OPLSDA
girder/viime pull request #676
Opened 2020-09-29 15:23 UTC by dchiquit

Now arbitrary datasets can be used with OPLSDA, as long as they have two or more groups defined.

I found an example of doing the group filtering in R, but I don't know how to write/debug R so I implemented it in the python view instead.

2020-09-30 21:08 UTC, subdavis requested changes
Looks like the group menus initialize out of sync with oplsda groups.  

## Steps to reproduce

1. use anovaTest dataset from e2e
1. upload, go to oplsda, see below

![Screenshot from 2020-09-30 17-03-15](https://user-images.githubusercontent.com/4214172/94739679-580cf800-033f-11eb-92d7-67fa70a096b9.png)

It looks like both the first and second group have to be changed once for them to sync up, then they work.  If you change the second group first, they're still out of sync until you change the first one.

2020-09-30 23:07 UTC, dchiquit commented
@subdavis Fixed, the group name list was different on the server, so the first two groups (which it defaults to) were different.

2020-10-01 18:59 UTC, subdavis requested changes
using the same dataset, when I first load the OPLSDA page, I still have this issue.  I pulled and rebuild the docker client image, then ran yarn serve to be sure.    Verified that your changes from 8ec3efaff2a3be8af69a6a7118d8cc7aa3c1bd6b are being built.

![Screenshot from 2020-10-01 14-57-11](https://user-images.githubusercontent.com/4214172/94851444-74b83700-03f6-11eb-800d-43aa7df2c498.png)

2020-10-05 15:36 UTC, dchiquit commented
I changed the behavior to just leave those fields blank when first loading the page.

2020-10-08 13:18 UTC, subdavis approved these changes
I don't think this behavior is ideal.  The drop-down selector does nothing when you change it (you have to change both), which will invariably be confusing to some users.  Maybe this can be addressed later.

2020-10-08 15:33 UTC, merged